### ISSUE TITLE
Dropdown menus - Show on hover

### ISSUE THREAD

**Issue by caarlos0** [gwtbootstrap/gwt-bootstrap#222]
I'd just made it work in a very simple way in a rails app, using a simple CSS hack..

``` css
ul.nav li.dropdown:hover ul.dropdown-menu{
    display: block;    
}
a.menu:after, .dropdown-toggle:after {
    content: none;
}
```

This way, when user hover the menu (in a menubar, e.g.), the dropdown is automagically shown.

I believe that we could made a option for this.. What do you think? If you agree I'll made that =)
