### ISSUE TITLE
tooltip on bootstrap modal is not working

### ISSUE THREAD

**Issue by amadamala** [gwtbootstrap/gwt-bootstrap#284]
Adding Tooltip to a widget and adding it to modal body is not working.
Reason is tooltip's z-index  is less than modal window z-index.

I can see following line in bootstrap.min.css 

``` css
.modal-open .modal .tooltip{z-index:2080;}
```

But tooltip is not being added outside of modal.

If you need any information please let know.
